#ifndef MODBUS_H
#define MODBUS_H


/* Modbus function codes */
#define MODBUS_FC_READ_COILS                0x01
#define MODBUS_FC_READ_DISCRETE_INPUTS      0x02
#define MODBUS_FC_READ_HOLDING_REGISTERS    0x03
#define MODBUS_FC_READ_INPUT_REGISTERS      0x04
#define MODBUS_FC_WRITE_SINGLE_COIL         0x05
#define MODBUS_FC_WRITE_SINGLE_REGISTER     0x06
#define MODBUS_FC_READ_EXCEPTION_STATUS     0x07
#define MODBUS_FC_WRITE_MULTIPLE_COILS      0x0F
#define MODBUS_FC_WRITE_MULTIPLE_REGISTERS  0x10
#define MODBUS_FC_REPORT_SLAVE_ID           0x11
#define MODBUS_FC_MASK_WRITE_REGISTER       0x16
#define MODBUS_FC_WRITE_AND_READ_REGISTERS  0x17

//Modbus Structure
#define MODBUS_LENGTH_TRANSACTION_IDENTIFIER 2
#define MODBUS_LENGTH_PROTOCOL_IDENTYFIER 2
#define MODBUS_LENGTH_LENGTH 2
#define MODBUS_LENGTH_UNIT_IDENTIFIER 1
#define MODBUS_LENGTH_FUNCTION_CODE 1

// |Transaction Identyfier x2| Protocol Identyfier x2| Length x2 | Unit Identyfier (must be 255) x1 | Function code x1| //

//
#endif // MODBUS_H

